# Generated by Django 4.0.5 on 2022-06-30 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
    ]
