# Generated by Django 4.0.5 on 2022-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_created_at_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
