# Generated by Django 4.0.5 on 2022-06-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='songcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
