# Generated by Django 4.0.5 on 2022-06-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_date_album_songcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songcount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
